/* src/primitives/s9.c */
void rehash(void);
int strcmp_ci(char *s1, char *s2);
void clear_trace(void);
void init_extensions(void);
void init_rts(void);
void init(void);
void load_initial_image(char *image);
void funny_char(char *msg, int c);
int block_comment(void);
int closing_paren(void);
void swap(void);
void stkalloc(int k);
int apply(int tail);
int applis(int tail);
int ret(void);
void entcol(int fix);
char *rev_cxr_name(char *s);
void loadfile(char *s);
void begin_rec(void);
void end_rec(void);
void keyboard_interrupt(int sig);
void keyboard_quit(int sig);
void mem_error(int src);
void reset_tty(void);
void repl(void);
void evalstr(char *s, int echo);
void usage(void);
void longusage(void);
long get_size_k(char *s);
char *cmdarg(char *s);
void CSL_S9_Init(void);
int s9_main(int argc, char **argv);
/* src/primitives/s9core.c */
void s9_run_stats(int x);
void s9_cons_stats(int x);
int s9_inport_open_p(void);
int s9_outport_open_p(void);
int s9_readc(void);
void s9_rejectc(int c);
void s9_writec(int c);
char *s9_open_input_string(char *s);
void s9_close_input_string(void);
void s9_flush(void);
void s9_set_printer_limit(int k);
int s9_printer_limit(void);
int s9_fwrite(char *s, int k);
void s9_blockwrite(char *s, int k);
int s9_blockread(char *s, int k);
void s9_prints(char *s);
int s9_io_status(void);
void s9_io_reset(void);
void s9_fatal(char *msg);
void s9_abort(void);
void s9_reset(void);
int s9_aborted(void);
void s9_set_node_limit(int n);
void s9_set_vector_limit(int n);
void s9_gc_verbosity(int n);
void s9_mem_error_handler(void (*h)(int src));
int s9_gc(void);
int s9_gcv(void);
unsigned hash(char *s);
int hash_size(int n);
long s9_asctol(char *s);
int s9_integer_string_p(char *s);
int s9_string_numeric_p(char *s);
void s9_close_port(int port);
int s9_new_port(void);
int s9_open_input_port(char *path);
int s9_open_output_port(char *path, int append);
int s9_port_eof(int p);
int s9_error_port(void);
int s9_input_port(void);
int s9_output_port(void);
void s9_reset_std_ports(void);
int s9_lock_port(int port);
int s9_unlock_port(int port);
char *s9_dump_image(char *path, char *magic);
char *s9_load_image(char *path, char *magic);
void s9_exponent_chars(char *s);
void CSL_S9Core_Init(void);
void s9_fini(void);
void fail(char *s);
void mem_error(int src);
void test_types(void);
void test_fixnum(void);
void test_bignum(void);
void test_real(void);
void test_io(void);
void test_conv(void);
void test_util(void);
int s9core_main(void);
