#include "../include/csl.h"

CPrimitive CPrimitives [] = {
    { "locationPush", 0, 0, 0, Location_PushNew, 0, 0, 0, "Experimental", "Root" },
    { "locationPrint", 0, 0, 0, CSL_Location_Printf, 0, 0, 0, "Experimental", "Root" },
    { "do>", 0, 0, 0, CSL_Do, IMMEDIATE, 0, 0, "Experimental", "Root" },
    { "does>", 0, 0, 0, CSL_Does, IMMEDIATE, 0, 0, "Experimental", "Root" },
    { "<do", 0, 0, 0, CSL_NoOp, IMMEDIATE, 0, 0, "Experimental", "Root" }, 

    { "(", 0, 0, 0, ( block ) LC_ReadEvalPrint_AfterAFirstLParen, IMMEDIATE | KEYWORD | LEFT_PAREN, 0, 0, "Lisp", "Root" },
    { "_(", 0, 0, 0, ( block ) LC_Read, IMMEDIATE | KEYWORD, 0, 0, "Lisp", "Root" },
    { "eval", 0, 0, 0, ( block ) LC_Eval, IMMEDIATE | KEYWORD, 0, 0, "Lisp", "Root" },
    { "print", 0, 0, 0, ( block ) LC_PrintWithValue, 0, 0, 0, "Lisp", "Root" },
    { ")", 0, 0, 0, CSL_C_Comma, IMMEDIATE | NO_OP_WORD | KEYWORD, 0, 0, "Lisp", "Root" },
    { "_Printf", 0, 0, 0, ( block ) Printf, 0, 0, LISP_C_RTL_ARGS | T_LISP_SPECIAL | LISP_VOID_RETURN, "Lisp", "Root" },
    { "define", 0, 0, 0, ( block ) LO_Define, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "compile", 0, 0, 0, ( block ) LO_CompileDefine, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "_lambda", 0, 0, 0, ( block ) LO_Lambda, IMMEDIATE, 0, T_LAMBDA | T_LISP_SPECIAL, "Lisp", "Root" },
    { "lambda", 0, 0, 0, ( block ) LO_Lambda, IMMEDIATE, 0, T_LAMBDA | T_LISP_SPECIAL, "Lisp", "Root" },
    { "begin", 0, 0, 0, ( block ) LO_Begin, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "set", 0, 0, 0, ( block ) LO_Set, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "let", 0, 0, 0, ( block ) LO_Let, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "if*", 0, 0, 0, ( block ) LO_Cond, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "macro", 0, 0, 0, ( block ) _LO_Macro, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" }, // nb. too many clashes with other 'if's
    { ".if", 0, 0, 0, ( block ) LO_Cond, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "cond", 0, 0, 0, ( block ) LO_Cond, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "car", 0, 0, 0, ( block ) LO_Car, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "cdr", 0, 0, 0, ( block ) LO_Cdr, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "quote", 0, 0, 0, ( block ) LO_Quote, 0, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "eval", 0, 0, 0, ( block ) _LC_Eval, 0, 0, T_LISP_SPECIAL, "Lisp", "Root" },
    { "list", 0, 0, 0, ( block ) LO_List, 0, 0, LIST_FUNCTION | T_LISP_SPECIAL, "Lisp", "Root" },
    { "'", 0, 0, 0, ( block ) LO_Quote, KEYWORD, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "@", 0, 0, 0, ( block ) LO_Splice, 0, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "quasiquote", 0, 0, 0, ( block ) LO_QuasiQuote, 0, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "`", 0, 0, 0, ( block ) LO_QuasiQuote, KEYWORD, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "unquote", 0, 0, 0, ( block ) LO_UnQuote, 0, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { ",", 0, 0, 0, ( block ) LO_UnQuote, 0, 0, T_LISP_READ_MACRO, "Lisp", "Root" },
    { "unquoteSplicing", 0, 0, 0, ( block ) LO_UnQuoteSplicing, 0, 0, T_LISP_UNQUOTE_SPLICING | T_LISP_READ_MACRO, "Lisp", "Root" },
    { ",@", 0, 0, 0, ( block ) LO_UnQuoteSplicing, 0, 0, T_LISP_UNQUOTE_SPLICING | T_LISP_READ_MACRO, "Lisp", "Root" },
    { "::", 0, 0, 0, ( block ) _LO_CSL, 0, 0, T_LISP_csl | T_LISP_SPECIAL | T_LISP_IMMEDIATE, "Lisp", "Root" },
    { "lcReset", 0, 0, 0, ( block ) LC_Reset, 0, 0, 0, "Lisp", "Root" },
    { "lcClearDefines", 0, 0, 0, ( block ) LC_ClearDefinesNamespace, 0, 0, 0, "Lisp", "Root" },

    { "'", 0, 0, 0, CSL_SingleQuote, IMMEDIATE | KEYWORD, 0, 0, "Forth", "Root" },
    { "1,", 0, 0, 0, Compile_Int8, 0, 0, 0, "Forth", "Root" },
    { "2,", 0, 0, 0, Compile_Int16, 0, 0, 0, "Forth", "Root" },
    { ",", 0, 0, 0, Compile_Int32, 0, 0, 0, "Forth", "Root" },
    { "4,", 0, 0, 0, Compile_Int32, 0, 0, 0, "Forth", "Root" },
    { "8,", 0, 0, 0, CompileInt64, 0, 0, 0, "Forth", "Root" },
    { "n,", 0, 0, 0, Compile_N_Bytes, 0, 0, 0, "Forth", "Root" },

    { "_Printf", 0, 0, 0, ( block ) Printf, LISP_C_RTL_ARGS | LISP_VOID_RETURN, 0, 0, "C", "Root" },
    { "printf", 0, 0, 0, ( block ) Printf, C_PREFIX_RTL_ARGS | LISP_VOID_RETURN, 0, 0, "C", "Root" },
    { "sprintf", 0, 0, 0, ( block ) sprintf, C_PREFIX_RTL_ARGS, 0, 0, "C", "Root" },
    //{ "()", 0, 0, 0, CSL_NoOp, IMMEDIATE, 0, 0, "C", "Root" },
    { "(", 0, 0, 0, CSL_C_LeftParen, IMMEDIATE | KEYWORD | LEFT_PAREN, 0, 0, "C", "Root" },
    { "(|", 0, 0, 0, CSL_LocalVariablesBegin, IMMEDIATE, 0, 0, "C", "Root" },
    { "if{", 0, 0, 0, CSL_If_ConditionalExpression, IMMEDIATE, 0, 0, "C", "Root" },
    { "}else{", 0, 0, 0, CSL_Else, IMMEDIATE, 0, 0, "C", "Root" },
    { "}fi", 0, 0, 0, CSL_EndIf, IMMEDIATE, 0, 0, "C", "Root" },
    { "case", 0, 0, 0, CSL_Case, IMMEDIATE, 0, 0, "C", "Root" },
    { "switch", 0, 0, 0, CSL_Switch, IMMEDIATE, 0, 0, "C", "Root" },
    { ">?", 0, 0, 0, CSL_EndIf, IMMEDIATE, 0, 0, "C", "Root" },
    { ">:<", 0, 0, 0, CSL_Else, IMMEDIATE, 0, 0, "C", "Root" },
    { "?<", 0, 0, 0, CSL_If_ConditionalExpression, IMMEDIATE, 0, 0, "C", "Root" },
    { "++", "I.I", 5, INC, CSL_PlusPlus, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_1_ARG | CATEGORY_PLUS_PLUS_MINUS_MINUS, 0, 0, "C", "Root" },
    { "--", "I.I", 5, DEC, CSL_MinusMinus, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_1_ARG | CATEGORY_PLUS_PLUS_MINUS_MINUS, 0, 0, "C", "Root" },
    { "cfib", 0, 0, 0, CFib, 0, 0, 0, "C", "Root" },
    { "cfactorial", 0, 0, 0, CFactorial, 0, 0, 0, "C", "Root" },
    { "cfactorial2", 0, 0, 0, CFactorial2, 0, 0, 0, "C", "Root" },
    { "cfactorial3", 0, 0, 0, CFactorial3, 0, 0, 0, "C", "Root" },
    { "ctct", 0, 0, 0, ctct, 0, 0, 0, "C", "Root" },
    { "cfib_O3", 0, 0, 0, CFib_O3, 0, 0, 0, "C", "Root" },
    { "cfib2_O3", 0, 0, 0, CFib2_O3, 0, 0, 0, "C", "Root" },
    { "cfactorial_O3", 0, 0, 0, CFactorial_O3, 0, 0, 0, "C", "Root" },
    { "cfactorial2_O3", 0, 0, 0, CFactorial2_O3, 0, 0, 0, "C", "Root" },
    { "cfactorial3_O3", 0, 0, 0, CFactorial3_O3, 0, 0, 0, "C", "Root" },
    { "c_rtl", 0, 0, 0, CSL_C_Prefix, IMMEDIATE, 0, 0, "C", "Root" },
    { "c_prefix", 0, 0, 0, CSL_C_Prefix, IMMEDIATE, 0, 0, "C", "Root" },
    { "c_return", 0, 0, 0, CSL_C_Return, IMMEDIATE, 0, 0, "C", "Root" },
    { "void_return", 0, 0, 0, CSL_Void_Return, IMMEDIATE, 0, 0, "C", "Root" },
    { "rax_return", 0, 0, 0, CSL_RAX_Return, IMMEDIATE, 0, 0, "C", "Root" },
    { ",", 0, 0, 0, CSL_C_Comma, IMMEDIATE | NO_OP_WORD | RIGHT_PAREN | KEYWORD, 0, 0, "C", "Root" },
    { "wordNameStructPrint", 0, 0, 0, CSL_Word_Name_ClassStructure_PrintData, 0, 0, 0, "C", "Root" },
    { "wordStructPrint", 0, 0, 0, CSL_Word_ClassStructure_PrintData, 0, 0, 0, "C", "Root" },

    { "{", 0, 0, 0, CSL_Begin_C_Block, IMMEDIATE | BLOCK_DELIMITER | KEYWORD, 0, 0, "C_Syntax", "C" },
    { "}", 0, 0, 0, CSL_End_C_Block, IMMEDIATE | BLOCK_DELIMITER | KEYWORD, 0, 0, "C_Syntax", "C" },
    { ";", 0, 0, 0, CSL_C_Semi, IMMEDIATE | SYNTACTIC | KEYWORD, 0, 0, "C_Syntax", "C" },
    { ",", 0, 0, 0, CSL_C_Comma, IMMEDIATE | NO_OP_WORD | RIGHT_PAREN | KEYWORD, 0, 0, "C_Syntax", "C" },
    { "!", 0, 0, TEST, CSL_LogicalNot, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_1_ARG | CATEGORY_LOGIC | PREFIX | LOGIC_NEGATE, 0, 0, "C_Syntax", "C" },
    { "?", 0, 0, 0, CSL_C_ConditionalExpression, COMBINATOR | IMMEDIATE, 0, 0, "C_Syntax", "C" },
    { "c_class", 0, 0, 0, ( block ) CSL_C_Class_New, 0, 0, 0, "C_Syntax", "C" },
    { "type", 0, 0, 0, ( block ) CSL_Type_New, 0, 0, 0, "C_Syntax", "C" },
    { "typedef", 0, 0, 0, CSL_Typedef, 0, 0, 0, "C_Syntax", "C" },
    { "&", 0, 0, 0, CSL_AddressOf, ( NO_CODING | ADDRESS_OF_OP | IMMEDIATE ), 0, 0, "C_Syntax", "C" }, // avoid name clash with '&&' and '&' 

    //{ "}", 0, 0, 0, CSL_TypedefStructEnd, IMMEDIATE | KEYWORD, 0, 0, "C_Typedef", "C_Syntax" },
    //{ "{", 0, 0, 0, CSL_TypedefStructBegin, IMMEDIATE | KEYWORD, 0, 0, "C_Typedef", "C_Syntax" },

    { "if", 0, 0, 0, CSL_If_PrefixCombinators, KEYWORD | COMBINATOR | IMMEDIATE, 0, 0, "PrefixCombinators", "C" },
    { "while", 0, 0, 0, CSL_While_PrefixCombinators, KEYWORD | COMBINATOR | IMMEDIATE, 0, 0, "PrefixCombinators", "C" },
    { "do", 0, 0, 0, CSL_DoWhile_PrefixCombinators, KEYWORD | COMBINATOR | IMMEDIATE, 0, 0, "PrefixCombinators", "C" },
    { "for", 0, 0, 0, CSL_For_PrefixCombinators, KEYWORD | COMBINATOR | IMMEDIATE, 0, 0, "PrefixCombinators", "C" },
    { "loop", 0, 0, 0, CSL_Loop_PrefixCombinators, KEYWORD | COMBINATOR | IMMEDIATE, 0, 0, "PrefixCombinators", "C" },

    //{ ":", 0, 0, 0, CSL_Colon, IMMEDIATE | KEYWORD, 0, 0, "Infix", "Compiler" },
    { "=", "XA.V", 0, MOV, ( block ) CSL_C_Infix_Equal, IMMEDIATE | CATEGORY_OP | INFIXABLE | CATEGORY_OP_EQUAL | KEYWORD, C_INFIX_OP_EQUAL, 0, "Infix", "C" }, //"Infix", "Compiler" },
    //{ "=", "XA.V", 0, MOV, ( block ) CSL_C_Infix_Equal, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_EQUAL | KEYWORD, C_INFIX_OP_EQUAL, 0, "Infix", "C" }, //"Infix", "Compiler" },

    { "(", 0, 0, 0, CSL_LocalsAndStackVariablesBegin, IMMEDIATE | KEYWORD | LEFT_PAREN, 0, 0, "Locals", "Root" },
    { "(|", 0, 0, 0, CSL_LocalVariablesBegin, IMMEDIATE, 0, 0, "Locals", "Root" },

    { "tf2", 0, 0, 0, CSL_TrueFalseCombinator2, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "tf3", 0, 0, 0, CSL_TrueFalseCombinator3, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "if1", 0, 0, 0, CSL_If1Combinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "if", 0, 0, 0, CSL_If2Combinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "if2", 0, 0, 0, CSL_If2Combinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "if3", 0, 0, 0, CSL_TrueFalseCombinator3, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "while", 0, 0, 0, ( block ) CSL_WhileCombinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "doWhile", 0, 0, 0, ( block ) CSL_DoWhileCombinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "doWhileDo", 0, 0, 0, CSL_DoWhileDoCombinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "call", 0, 0, 0, CSL_BlockRun, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "run", 0, 0, 0, CSL_BlockRun, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "_call", 0, 0, 0, CSL_BlockRun, COMBINATOR, 0, 0, "Combinators", "Root" },
    { "_run", 0, 0, 0, CSL_BlockRun, COMBINATOR, 0, 0, "Combinators", "Root" },
    { "_", 0, 0, 0, CSL_DropBlock, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "loop", 0, 0, 0, CSL_LoopCombinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "for", 0, 0, 0, CSL_ForCombinator, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },
    { "?", 0, 0, 0, CSL_C_ConditionalExpression, COMBINATOR | IMMEDIATE, 0, 0, "Combinators", "Root" },

    { "in", 0, 0, 0, CSL_PrintInNamespace, 0, 0, 0, "Namespace", "Root" },
    { "using", 0, 0, 0, CSL_Using, 0, 0, 0, "Namespace", "Root" },
    { "usingWAddress", 0, 0, 0, CSL_Using_WithAddress, 0, 0, 0, "Namespace", "Root" },
    { "usingFirst", 0, 0, 0, CSL_Namespace_UsingFirst, 0, 0, 0, "Namespace", "Root" },
    { "usingLast", 0, 0, 0, CSL_Namespace_UsingLast, 0, 0, 0, "Namespace", "Root" },
    { "notUsing", 0, 0, 0, CSL_Namespace_NotUsing, 0, 0, 0, "Namespace", "Root" },
    { "setStateNotUsing", 0, 0, 0, CSL_Namespace_SetStateAs_NotUsing, 0, 0, 0, "Namespace", "Root" },
    { "setStateUsing", 0, 0, 0, CSL_Namespace_SetStateAs_Using, 0, 0, 0, "Namespace", "Root" },
    { "namespaces", 0, 0, 0, CSL_Namespaces, 0, 0, 0, "Namespace", "Root" },
    { "namespaceTree", 0, 0, 0, CSL_Namespaces_PrettyPrintTree, 0, 0, 0, "Namespace", "Root" },
    { "namespaceTreeWithWords", 0, 0, 0, CSL_Namespaces_PrettyPrintTreeWithWords, 0, 0, 0, "Namespace", "Root" },
    { "words", 0, 0, 0, CSL_Words, 0, 0, 0, "Namespace", "Root" },
    { "allWords", 0, 0, 0, CSL_AllWords, 0, 0, 0, "Namespace", "Root" },
    { "_namespaceWords", 0, 0, 0, _CSL_NamespaceWords, 0, 0, 0, "Namespace", "Root" },
    { "namespaceWords", 0, 0, 0, CSL_NamespaceWords, 0, 0, 0, "Namespace", "Root" },
    { "namespace", 0, 0, 0, CSL_Namespace_New, 0, 0, 0, "Namespace", "Root" },
    //{ "sealed", 0, 0, 0, CSL_NamespaceSealed, 0, 0, 0, "Namespace", "Root" },
    { "_findUsing", 0, 0, 0, CSL_Postfix_Find_Using, 0, 0, 0, "Namespace", "Root" },
    { "_findAny", 0, 0, 0, CSL_Postfix_Find_Any, 0, 0, 0, "Namespace", "Root" },

    { "};", 0, 0, 0, CSL_ClassStructureEnd, 0, 0, 0, "Class", "Root" },
    { "+:{", 0, 0, 0, CSL_CloneStructureBegin, 0, 0, 0, "Class", "Root" },
    { ":{", 0, 0, 0, CSL_ClassTypedef, 0, 0, 0, "Class", "Root" },
    { "class", 0, 0, 0, CSL_Class_New, 0, 0, 0, "Class", "Root" },
    { "struct", 0, 0, 0, CSL_Class_New, 0, 0, 0, "Class", "Root" },
    { "new", 0, 0, 0, ( block ) CSL_Class_Object_New, 0, 0, 0, "Class", "Root" },
    { "clone", 0, 0, 0, CSL_Class_Clone, 0, 0, 0, "Class", "Root" },
    { "]", 0, 0, 0, CSL_ArrayEnd, ( IMMEDIATE | OBJECT_OPERATOR ), RIGHT_BRACKET, 0, "Class", "Root" },
    { "[", 0, 0, 0, CSL_ArrayBegin, ( IMMEDIATE | OBJECT_OPERATOR ), COMPILER_LEFT_BRACKET, 0, "Class", "Root" },
    { ".", 0, 0, 0, CSL_Dot, ( IMMEDIATE | OBJECT_OPERATOR | NO_CODING ), 0, 0, "Class", "Root" },

    { "pWidth", 0, 0, 0, BigNum_Set_PrintfWidth, 0, 0, 0, "BigNum", "Class" },
    { "pPrecision", 0, 0, 0, BigNum_Set_PrintfPrecision, 0, 0, 0, "BigNum", "Class" },
    { "bnState", 0, 0, 0, BigNum_StateShow, 0, 0, 0, "BigNum", "Class" },

    { "+", "NN.N", 0, 0, BigNum_Add, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "-", "NN.N", 0, 0, BigNum_Subtract, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "+=", "NN.N", 0, 0, BigNum_PlusEqual, 0, 0, 0, "BigNum", "Class" },
    { "++", "N.N", 0, 0, BigNum_PlusPlus, 0, 0, 0, "BigNum", "Class" },
    { "-=", "NN.N", 0, 0, BigNum_MinusEqual, 0, 0, 0, "BigNum", "Class" },
    { "--", "N.N", 0, 0, BigNum_MinusMinus, 0, 0, 0, "BigNum", "Class" },
    { "*", "NN.N", 0, 0, BigNum_Multiply, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "*=", "NN.N", 0, 0, BigNum_MultiplyEqual, 0, 0, 0, "BigNum", "Class" },
    //{ "^", "NN.N", 0, 0, BigNum_Power, 0, 0, 0, "BigNum", "Class" },
    { "/", "NN.N", 0, 0, BigNum_Divide, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "/=", "NN.N", 0, 0, BigNum_DivideEqual, 0, 0, 0, "BigNum", "Class" },
    { "==", "NN.B", 0, 0, ( block ) BigNum_Equal, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "<=", "NN.B", 0, 0, ( block ) BigNum_LessThanOrEqual, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "<", "NN.B", 0, 0, ( block ) BigNum_LessThan, INFIXABLE, 0, 0, "BigNum", "Class" },
    { ">=", "NN.B", 0, 0, ( block ) BigNum_GreaterThanOrEqual, INFIXABLE, 0, 0, "BigNum", "Class" },
    { ">", "NN.B", 0, 0, ( block ) BigNum_GreaterThan, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "==", "NN.B", 0, 0, ( block ) BigNum_LogicalEquals, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "!=", "NN.B", 0, 0, ( block ) BigNum_LogicalDoesNotEqual, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "sqrt", "N.N", 0, 0, ( block ) BigNum_SquareRoot, 0, 0, 0, "BigNum", "Class" },
    { "pow", "NN.N", 0, 0, ( block ) BigNum_Power, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "^", "NN.N", 0, 0, ( block ) BigNum_Power, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "**", "NN.N", 0, 0, ( block ) BigNum_Power, INFIXABLE, 0, 0, "BigNum", "Class" },
    { "_eprint", 0, 0, 0, BigNum_EPrint, 0, 0, 0, "BigNum", "Class" },
    { "_fprint", 0, 0, 0, BigNum_FPrint, 0, 0, 0, "BigNum", "Class" },

    { "||", 0, 1, OR, CSL_LogicalOr, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "or", 0, 1, OR, CSL_LogicalOr, IMMEDIATE | KEYWORD | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "xor", 0, 1, XOR, CSL_LogicalXor, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE, 0, 0, "Logic", "Root" },
    { "^^", 0, 1, XOR, CSL_LogicalXor, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE, 0, 0, "Logic", "Root" },
    { "!", 0, 0, TEST, CSL_LogicalNot, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_1_ARG | CATEGORY_LOGIC | LOGIC_NEGATE, 0, 0, "Logic", "Root" },
    { "not", 0, 0, TEST, CSL_LogicalNot, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_1_ARG | CATEGORY_LOGIC | LOGIC_NEGATE, 0, 0, "Logic", "Root" },
    { "and", 0, 0, TEST, CSL_LogicalAnd, IMMEDIATE | KEYWORD | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },
    { "&&", 0, 1, CMP, CSL_LogicalAnd, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE, 0, 0, "Logic", "Root" },
    { "<", "II.B", 1, CMP, CSL_LessThan, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_LOGIC | INFIXABLE, 0, 0, "Logic", "Root" },
    { ">", "II.B", 1, CMP, CSL_GreaterThan, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_LOGIC | INFIXABLE, 0, 0, "Logic", "Root" },
    { "==", "II.B", 1, CMP, CSL_Equals, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE, 0, 0, "Logic", "Root" },
    { "equal", "II.B", 1, CMP, CSL_Equals, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC, 0, 0, "Logic", "Root" },
    { "!=", "II.B", 1, CMP, CSL_DoesNotEqual, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | CATEGORY_LOGIC | INFIXABLE | LOGIC_NEGATE, 0, 0, "Logic", "Root" },
    { "<=", "II.B", 1, CMP, CSL_LessThanOrEqual, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_LOGIC | INFIXABLE, 0, 0, "Logic", "Root" },
    { ">=", "II.B", 1, CMP, CSL_GreaterThanOrEqual, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_LOGIC | INFIXABLE | KEYWORD, 0, 0, "Logic", "Root" },

    { "+", "II.I", 1, ADD, CSL_Plus, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | INFIXABLE, 0, 0, "Int", "Root" },
    { "-", "II.I", 1, SUB, CSL_Minus, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | INFIXABLE, 0, 0, "Int", "Root" },
    { "+=", 0, 1, ADD, CSL_PlusEqual, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_OPEQUAL | INFIXABLE, 0, 0, "Int", "Root" },
    { "-=", 0, 1, SUB, CSL_MinusEqual, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_OPEQUAL | INFIXABLE, 0, 0, "Int", "Root" },
    { "*", "II.I", 3, MUL, CSL_Multiply, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | INFIXABLE, 0, 0, "Int", "Root" },
    { "**", "II.I", 0, 0, CSL_Power, CATEGORY_OP_ORDERED | KEYWORD | CATEGORY_OP | INFIXABLE, 0, 0, "Int", "Root" },
    { "pow", "II.I", 0, 0, CSL_Power, CATEGORY_OP_ORDERED | CATEGORY_OP | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "pow_03", "II.I", 0, 0, CSL_Power_03, CATEGORY_OP_ORDERED | CATEGORY_OP | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "^", "II.I", 0, 0, CSL_Power, CATEGORY_OP_ORDERED | KEYWORD | CATEGORY_OP | INFIXABLE, 0, 0, "Int", "Root" },
    { "/", "II.I", 3, DIV, CSL_Divide, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_DIVIDE | CATEGORY_OP_ORDERED | INFIXABLE | OP_RAX_PLUS_1ARG, 0, 0, "Int", "Root" },
    { "modulo", 0, 3, MODULO, CSL_Mod, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_DIVIDE | INFIXABLE | KEYWORD, 0, 0, "Int", "Root" },
    { "%", "II.I", 3, DIV, CSL_Mod, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_DIVIDE | CATEGORY_OP_ORDERED | INFIXABLE, 0, 0, "Int", "Root" },
    { "*=", "II.I", 3, MUL, CSL_MultiplyEqual, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_OPEQUAL | INFIXABLE, 0, 0, "Int", "Root" },
    { "/=", "II.I", 3, DIV, CSL_DivideEqual, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_OPEQUAL | CATEGORY_OP_ORDERED | INFIXABLE | OP_RAX_PLUS_1ARG, 0, 0, "Int", "Root" },
    { "intPrint", 0, 0, 0, CSL_PrintInt, 0, 0, 0, "Int", "Root" },
    { "hexIntPrint", 0, 0, 0, CSL_HexPrintInt, 0, 0, 0, "Int", "Root" },

    { "<<", "I.I", 2, SHL, CSL_ShiftLeft, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | BIT_SHIFT | INFIXABLE, 0, 0, "Bits", "Logic" },
    { ">>", "I.I", 2, SHR, CSL_ShiftRight, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | BIT_SHIFT | INFIXABLE, 0, 0, "Bits", "Logic" },
    { "&", "II.I", 1, AND, CSL_BitWise_AND, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | INFIXABLE, 0, 0, "Bits", "Logic" },
    { "|", "II.I", 1, OR, CSL_BitWise_OR, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED | INFIXABLE, 0, 0, "Bits", "Logic" },
    { "^", "II.I", 1, XOR, CSL_BitWise_XOR, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_UNORDERED, 0, 0, "Bits", "Logic" },
    { "~", "I.I", 3, NOT, CSL_BitWise_NOT, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_1_ARG, 0, 0, "Bits", "Logic" },
    { "neg", "I.I", 3, NEG, CSL_BitWise_NEG, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_1_ARG, 0, 0, "Bits", "Logic" },
    { "<<=", 0, 2, SHL, CSL_ShiftLeft_Equal, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_OP_OPEQUAL | BIT_SHIFT | INFIXABLE, 0, 0, "Bits", "Logic" },
    { ">>=", 0, 2, SHR, CSL_ShiftRight_Equal, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_OP_OPEQUAL | BIT_SHIFT | INFIXABLE, 0, 0, "Bits", "Logic" },
    { "&=", 0, 1, AND, CSL_BitWise_AndEqual, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_OP_OPEQUAL | INFIXABLE, 0, 0, "Bits", "Logic" },
    { "|=", 0, 1, OR, CSL_BitWise_OrEqual, IMMEDIATE | KEYWORD | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_OP_OPEQUAL | INFIXABLE, 0, 0, "Bits", "Logic" },

    { "_fi", 0, 0, 0, CSL_EndIf, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "_else_", 0, 0, 0, CSL_Else, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "if_", 0, 0, 0, CSL_If_ConditionalExpression, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "Jmp", 0, 0, 0, CSL_JMP, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "jmpHere", 0, 0, 0, CSL_JmpToHere, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "Jcc", 0, 0, 0, CSL_Compile_Jcc, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "jcc", 0, 0, 0, CSL_Jcc_Label, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "label", 0, 0, 0, CSL_Label, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "goto", 0, 0, 0, CSL_Goto, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "label:", 0, 0, 0, CSL_Label_Prefix, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "goto:", 0, 0, 0, CSL_Goto_Prefix, IMMEDIATE, 0, 0, "Asm", "Root" },
    { "jmp", 0, 0, 0, CSL_Goto, IMMEDIATE, 0, 0, "Asm", "Root" },

    { "Strlen", 0, 0, 0, CSL_Strlen, 0, 0, 0, "String", "Root" },
    { "strcmp", 0, 0, 0, CSL_Strcmp, 0, 0, 0, "String", "Root" },
    { "strcat", 0, 0, 0, CSL_StrCat, 0, 0, 0, "String", "Root" },
    { "strcpy", 0, 0, 0, CSL_StrCpy, 0, 0, 0, "String", "Root" },
    { "stricmp", 0, 0, 0, CSL_Stricmp, 0, 0, 0, "String", "Root" },

    { "\"", 0, 0, 0, CSL_DoubleQuoteMacro, IMMEDIATE | KEYWORD | CATEGORY_OP_STACK, 0, T_LISP_TERMINATING_MACRO, "Lexer", "Root" },
    { "%", 0, 0, 0, MultipleEscape, IMMEDIATE, 0, 0, "Lexer", "Root" },

    { "printString", "S.V", 0, 0, CSL_PrintString, 0, 0, 0, "Io", "Root" },
    { "emit", 0, 0, 0, CSL_Emit, 0, 0, 0, "Io", "Root" },
    { "key", 0, 0, 0, CSL_Key, 0, 0, 0, "Io", "Root" },
    { "kbhit", 0, 0, 0, CSL_Kbhit, 0, 0, 0, "Io", "Root" },
    { "newline", 0, 0, 0, CSL_NewLine, 0, 0, 0, "Io", "Root" },
    { "cr", 0, 0, 0, CSL_CarriageReturn, 0, 0, 0, "Io", "Root" },
    { "tab", 0, 0, 0, CSL_TAB, 0, 0, 0, "Io", "Root" },
    { "space", 0, 0, 0, CSL_SPACE, 0, 0, 0, "Io", "Root" },
    { "logAppend", 0, 0, 0, CSL_LogAppend, 0, 0, 0, "Io", "Root" },
    { "logWrite", 0, 0, 0, CSL_LogWrite, 0, 0, 0, "Io", "Root" },
    { "logOn", 0, 0, 0, CSL_LogOn, 0, 0, 0, "Io", "Root" },
    { "logOff", 0, 0, 0, CSL_LogOff, 0, 0, 0, "Io", "Root" },

    { "dump", 0, 0, 0, CSL_Dump, 0, 0, 0, "Debug", "Root" },
    { "dis", 0, 0, 0, CSL_Disassemble, 0, 0, 0, "Debug", "Root" },
    { "bdis", 0, 0, 0, CSL_Disassemble_Block, 0, 0, 0, "Debug", "Root" },
    { "wordDisassemble", 0, 0, 0, CSL_Word_Disassemble, 0, 0, 0, "Debug", "Root" },
    { "sourceAdd", 0, 0, 0, CSL_Source_AddToHistory, 0, 0, 0, "Debug", "Root" },
    { "source", 0, 0, 0, CSL_Source_AddToHistory, 0, 0, 0, "Debug", "Root" },
    { "sourceDontAdd", 0, 0, 0, CSL_Source_DontAddToHistory, 0, 0, 0, "Debug", "Root" },
    { "setSourceCodeWord", 0, 0, 0, CSL_SetSourceCodeWord, 0, 0, 0, "Debug", "Root" },
    { "stack", 0, 0, 0, CSL_PrintDataStack, 0, 0, 0, "Debug", "Root" },
    { "stackDepthPrint", 0, 0, 0, CSL_PrintStackDepth, 0, 0, 0, "Debug", "Root" },
    { "rstack", 0, 0, 0, CSL_PrintReturnStack, 0, 0, 0, "Debug", "Root" },
    { "nrstack", 0, 0, 0, CSL_PrintNReturnStack, 0, 0, 0, "Debug", "Root" },
    { "dstack", 0, 0, 0, CSL_PrintNDataStack_8, 0, 0, 0, "Debug", "Root" },
    { "ndstack", 0, 0, 0, CSL_PrintNDataStack, 0, 0, 0, "Debug", "Root" },
    //{ "s{", 0, 0, 0, CSL_DbgSourceCodeBeginBlock, IMMEDIATE, BLOCK_DELIMITER, 0, "Debug", "Root" },
    //{ "}s", 0, 0, 0, CSL_DbgSourceCodeEndBlock, IMMEDIATE, BLOCK_DELIMITER, 0, "Debug", "Root" },
    //{ "s:", 0, 0, 0, CSL_SourceCodeCompileOn_Colon, IMMEDIATE, 0, 0, "Debug", "Root" },
    //{ ";s", 0, 0, 0, CSL_SourceCodeCompileOff_SemiColon, IMMEDIATE, 0, 0, "Debug", "Root" },
    { "dbgSourceCodeOn", 0, 0, 0, CSL_DbgSourceCodeOn_Global, IMMEDIATE, 0, 0, "Debug", "Root" },
    { "dbgSourceCodeOff", 0, 0, 0, CSL_DbgSourceCodeOff_Global, IMMEDIATE, 0, 0, "Debug", "Root" },
    { "dbgTypecheckOn", 0, 0, 0, CSL_DbgTypecheckOn, 0, 0, 0, "Debug", "Root" },
    //{ "}t", 0, 0, 0, CSL_DbgTypecheckOn, 0, 0, 0, "Debug", "Root" },
    { "dbgTypecheckOff", 0, 0, 0, CSL_DbgTypecheckOff, 0, 0, 0, "Debug", "Root" },
    //{ "t{", 0, 0, 0, CSL_DbgTypecheckOff, 0, 0, 0, "Debug", "Root" },
    { "scOff", 0, 0, 0, CSL_DbgSourceCodeOff, 0, 0, 0, "Debug", "Root" },
    { "scOn", 0, 0, 0, CSL_DbgSourceCodeOn, 0, 0, 0, "Debug", "Root" },
    { "_dbgOn", 0, 0, 0, CSL_DebugOn, DEBUG_WORD | INTERPRET_DBG, 0, 0, "Debug", "Root" },
    { "_dbgOff", 0, 0, 0, CSL_DebugOff, INTERPRET_DBG, 0, 0, "Debug", "Root" },
    { ";d", 0, 0, 0, CSL_DebugOff, DEBUG_WORD | INTERPRET_DBG, 0, 0, "Debug", "Root" },
    { "xtDbg", 0, 0, 0, CSL_Debug_AtAddress, DEBUG_WORD | INTERPRET_DBG, 0, 0, "Debug", "Root" },
    { "_info", 0, 0, 0, _CSL_DebugInfo, 0, 0, 0, "Debug", "Root" },
    { "info", 0, 0, 0, CSL_DebugInfo, 0, 0, 0, "Debug", "Root" },
    { "localsShow", 0, 0, 0, _CSL_Debugger_Locals_Show, DEBUG_WORD, 0, 0, "Debug", "Root" },
    { "stop", 0, 0, 0, CSL_DebugStop, DEBUG_WORD, 0, 0, "Debug", "Root" },

    { "_include", 0, 0, 0, CSL_IncludeFile, 0, 0, 0, "System", "Root" },
    { "reset", 0, 0, 0, CSL_WarmInit, 0, 0, 0, "System", "Root" },
    { "stackInit", 0, 0, 0, CSL_DataStack_Init, 0, 0, 0, "System", "Root" },
    { "stackDepth", 0, 0, 0, CSL_DataStack_Size, 0, 0, 0, "System", "Root" },
    { "filename", 0, 0, 0, CSL_Filename, 0, 0, 0, "System", "Root" },
    { "throw", 0, 0, 0, CSL_Throw, 0, 0, 0, "System", "Root" },
    { "lineNumber", 0, 0, 0, CSL_LineNumber, 0, 0, 0, "System", "Root" },
    { "charNumber", 0, 0, 0, CSL_LineCharacterNumber, 0, 0, 0, "System", "Root" },
    { "version", 0, 0, 0, CSL_Version, 0, 0, 0, "System", "Root" },
    { "decimal", 0, 0, 0, CSL_Decimal, 0, 0, 0, "System", "Root" },
    { "hex", 0, 0, 0, CSL_Hex, 0, 0, 0, "System", "Root" },
    { "binary", 0, 0, 0, CSL_Binary, 0, 0, 0, "System", "Root" },
    { "state", 0, 0, 0, CSL_SystemState_Print, 0, 0, 0, "System", "Root" },
    { "variables", 0, 0, 0, CSL_Variables, 0, 0, 0, "System", "Root" },
    { "echoOff", 0, 0, 0, CSL_EchoOff, 0, 0, 0, "System", "Root" },
    { "echoOn", 0, 0, 0, CSL_EchoOn, 0, 0, 0, "System", "Root" },
    { "echoOff", 0, 0, 0, CSL_EchoOff, 0, 0, 0, "System", "Root" },
    { "jcc8_On", 0, 0, 0, CSL_Jcc8_On, 0, 0, 0, "System", "Root" },
    { "jcc8_Off", 0, 0, 0, CSL_Jcc8_Off, 0, 0, 0, "System", "Root" },
    { "echo", 0, 0, 0, CSL_Echo, IMMEDIATE, 0, 0, "System", "Root" },
    { "timeInit", 0, 0, 0, CSL_InitTime, 0, 0, 0, "System", "Root" },
    { "timerInit", 0, 0, 0, CSL_TimerInit, 0, 0, 0, "System", "Root" },
    { "time", 0, 0, 0, CSL_Time, 0, 0, 0, "System", "Root" },
    { "shell", 0, 0, 0, CSL_ShellEscape, 0, 0, 0, "System", "Root" },
    { "system0", 0, 0, 0, CSL_system0, 0, 0, 0, "System", "Root" },
    { "system1", 0, 0, 0, CSL_system1, 0, 0, 0, "System", "Root" },
    { "system2", 0, 0, 0, CSL_system2, 0, 0, 0, "System", "Root" },
    { "system3", 0, 0, 0, CSL_system3, 0, 0, 0, "System", "Root" },
    { "returnFromFile", 0, 0, 0, CSL_ReturnFromFile, 0, 0, 0, "System", "Root" },
    { "allocateMem", 0, 0, 0, CSL_AllocateNew, 0, 0, 0, "System", "Root" },
    { "freeSessionMem", 0, 0, 0, OVT_MemListFree_Session, 0, 0, 0, "System", "Root" },
    { "mem", 0, 0, 0, OVT_ShowMemoryAllocated, 0, 0, 0, "System", "Root" },
    { "resetAll", 0, 0, 0, CSL_ResetAll, 0, 0, 0, "System", "Root" },
    { "bye", 0, 0, 0, OVT_Exit, 0, 0, 0, "System", "Root" },
    { "abort", 0, 0, 0, CSL_Abort, 0, 0, 0, "System", "Root" },
    { "quit", 0, 0, 0, CSL_Quit, 0, 0, 0, "System", "Root" },
    { "systemBreak", 0, 0, 0, CSL_SystemBreak, 0, 0, 0, "System", "Root" },
    { "exit", 0, 0, 0, OVT_Exit, 0, 0, 0, "System", "Root" },
    { "restart", 0, 0, 0, CSL_Restart, 0, 0, 0, "System", "Root" },
    { "restartInit", 0, 0, 0, CSL_RestartInit, 0, 0, 0, "System", "Root" },
    { "ri", 0, 0, 0, CSL_RestartInit, 0, 0, 0, "System", "Root" },
    { "fullRestart", 0, 0, 0, CSL_FullRestart, 0, 0, 0, "System", "Root" },
    { "fr", 0, 0, 0, CSL_FullRestart, 0, 0, 0, "System", "Root" },
    { "warmInit", 0, 0, 0, CSL_WarmInit, 0, 0, 0, "System", "Root" },
    { "ok", 0, 0, 0, OVT_Ok, 0, 0, 0, "System", "Root" },
    { "console", 0, 0, 0, Console, 0, 0, 0, "System", "Root" },
    { "cpuStateShow", 0, 0, 0, CSL_CpuState_CheckShow, 0, 0, 0, "System", "Root" },
    { "showTypeWordStack", 0, 0, 0, CSL_ShowTypeWordStack, 0, 0, 0, "System", "Root" },
    { "location", 0, 0, 0, CSL_Location, 0, 0, 0, "System", "Root" },
    { "pause", 0, 0, 0, OpenVmTil_Pause, 0, 0, 0, "System", "Root" },
    { "_pause", 0, 0, 0, OpenVmTil_Pause, 0, 0, 0, "System", "Root" },
    { "registers", 0, 0, 0, _Debugger_CpuState_Show, 0, 0, 0, "System", "Root" },
    { "lcOn", 0, 0, 0, ( block ) LC_On, 0, 0, 0, "System", "Root" },
    { "lcOff", 0, 0, 0, ( block ) LC_LispNamespacesOff, 0, 0, 0, "System", "Root" },

    { "if", 0, 0, 0, CSL_If_ConditionalExpression, IMMEDIATE, 0, 0, "Shell", "Root" },
    { "else", 0, 0, 0, CSL_Else, IMMEDIATE, 0, 0, "Shell", "Root" },
    { "endif", 0, 0, 0, CSL_EndIf, IMMEDIATE, 0, 0, "Shell", "Root" },
    { "_sh", 0, 0, 0, ShellEscape_Postfix, 0, 0, 0, "Shell", "Root" },
    { "$", 0, 0, 0, _shell, 0, 0, 0, "Shell", "Root" },
    { "sh", 0, 0, 0, shell, 0, 0, 0, "Shell", "Root" },

    { "fopen", 0, 0, 0, File_Open, CATEGORY_OP_STACK, 0, 0, "File", "System" },
    { "fclose", 0, 0, 0, File_Close, 0, 0, 0, "File", "System" },
    { "fwrite", 0, 0, 0, File_Write, 0, 0, 0, "File", "System" },
    { "fread", 0, 0, 0, File_Read, CATEGORY_OP_STACK, 0, 0, "File", "System" },
    { "fseek", 0, 0, 0, File_Seek, 0, 0, 0, "File", "System" },
    { "ftell", 0, 0, 0, File_Tell, CATEGORY_OP_STACK, 0, 0, "File", "System" },
    { "fsize", 0, 0, 0, File_Size, CATEGORY_OP_STACK, 0, 0, "File", "System" },
    { "fexists", 0, 0, 0, File_Exists, CATEGORY_OP_STACK, 0, 0, "File", "System" },
    { "freadToString", 0, 0, 0, File_ReadToString, 0, 0, 0, "File", "System" },

    { "setDefaultRGB", 0, 0, 0, CSL_SetDefaultRGB, 0, 0, 0, "Colors", "System" },
    { "setAlertRGB", 0, 0, 0, CSL_SetAlertRGB, 0, 0, 0, "Colors", "System" },
    { "setDebugRGB", 0, 0, 0, CSL_SetDebugRGB, 0, 0, 0, "Colors", "System" },
    { "setUserRGB", 0, 0, 0, CSL_SetDebugRGB, 0, 0, 0, "Colors", "System" },
    { "setNoticeRGB", 0, 0, 0, CSL_SetNoticeRGB, 0, 0, 0, "Colors", "System" },
    { "setUserColors", 0, 0, 0, CSL_SetUserColors, 0, 0, 0, "Colors", "System" },
    { "setDefaultColors", 0, 0, 0, CSL_SetDefaultColors, 0, 0, 0, "Colors", "System" },
    { "setAlertColors", 0, 0, 0, CSL_SetAlertColors, 0, 0, 0, "Colors", "System" },
    { "setDebugColors", 0, 0, 0, CSL_SetDebugColors, 0, 0, 0, "Colors", "System" },
    { "setNoticeColors", 0, 0, 0, CSL_SetNoticeColors, 0, 0, 0, "Colors", "System" },
    { "debugColors", 0, 0, 0, Ovt_DebugColors, 0, 0, 0, "Colors", "System" },
    { "noticeColors", 0, 0, 0, Ovt_NoticeColors, 0, 0, 0, "Colors", "System" },
    { "defaultColors", 0, 0, 0, Ovt_DefaultColors, 0, 0, 0, "Colors", "System" },
    { "userColors", 0, 0, 0, Ovt_UserColors, 0, 0, 0, "Colors", "System" },
    { "alertColors", 0, 0, 0, Ovt_AlertColors, 0, 0, 0, "Colors", "System" },

    { "autoVar", 0, 0, 0, Ovt_AutoVar, 0, 0, 0, "OpenVmTil", "Root" },
    { "autoVarOn", 0, 0, 0, Ovt_AutoVarOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "autoVarOff", 0, 0, 0, Ovt_AutoVarOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "optimize", 0, 0, 0, Ovt_Optimize, 0, 0, 0, "OpenVmTil", "Root" },
    { "inlining", 0, 0, 0, Ovt_Inlining, 0, 0, 0, "OpenVmTil", "Root" },
    { "typecheckOn", 0, 0, 0, CSL_TypeCheckOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "typecheckOff", 0, 0, 0, CSL_TypeCheckOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "}t", 0, 0, 0, CSL_TypeCheckOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "t{", 0, 0, 0, CSL_TypeCheckOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "optimizeOn", 0, 0, 0, CSL_OptimizeOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "optimizeOff", 0, 0, 0, CSL_OptimizeOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "stringMacrosOn", 0, 0, 0, CSL_StringMacrosOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "stringMacrosOff", 0, 0, 0, CSL_StringMacrosOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "inlineOff", 0, 0, 0, CSL_InlineOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "inlineOn", 0, 0, 0, CSL_InlineOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "debugOff", 0, 0, 0, CSL_DebugOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "debugOn", 0, 0, 0, CSL_DebugOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "debugLevel", 0, 0, 0, CSL_DebugLevel, IMMEDIATE|NAMESPACE_VARIABLE, 0, 0, "OpenVmTil", "Root" },
    { "verbosity", 0, 0, 0, OpenVmTil_Verbosity, IMMEDIATE|NAMESPACE_VARIABLE, 0, 0, "OpenVmTil", "Root" },
    { "dbi", 0, 0, 0, OpenVmTil_ShowMachineCodeInstructions, IMMEDIATE|NAMESPACE_VARIABLE, 0, 0, "OpenVmTil", "Root" },
    { "codeSize", 0, 0, 0, OpenVmTil_CodeSize, 0, 0, 0, "OpenVmTil", "Root" },
    { "objectsSize", 0, 0, 0, OpenVmTil_ObjectsSize, 0, 0, 0, "OpenVmTil", "Root" },
    { "compilerTempObjectsSize", 0, 0, 0, OpenVmTil_CompilerTempObjectsSize, 0, 0, 0, "OpenVmTil", "Root" },
    { "sessionObjectsSize", 0, 0, 0, OpenVmTil_SessionObjectsSize, 0, 0, 0, "OpenVmTil", "Root" },
    { "dictionarySize", 0, 0, 0, OpenVmTil_DictionarySize, 0, 0, 0, "OpenVmTil", "Root" },
    { "dataStackSize", 0, 0, 0, OpenVmTil_DataStackSize, 0, 0, 0, "OpenVmTil", "Root" },
    { "historySize", 0, 0, 0, OpenVmTil_HistorySize, 0, 0, 0, "OpenVmTil", "Root" },
    { "addToHistory", 0, 0, 0, OpenVmTil_AddStringToHistory, 0, 0, 0, "OpenVmTil", "Root" },
    { "historyReset", 0, 0, 0, HistorySpace_Reset, 0, 0, 0, "OpenVmTil", "Root" },
    { "addToHistoryOn", 0, 0, 0, OpenVmTil_AddStringToHistoryOn, 0, 0, 0, "OpenVmTil", "Root" },
    { "addToHistoryOff", 0, 0, 0, OpenVmTil_AddStringToHistoryOff, 0, 0, 0, "OpenVmTil", "Root" },
    { "showAllocated", 0, 0, 0, OVT_Mem_ShowAllocated, 0, 0, 0, "OpenVmTil", "Root" },
    { "recycleDebugInfo", 0, 0, 0, OVT_RecycleAllWordsDebugInfo, 0, 0, 0, "OpenVmTil", "Root" },

    { "freeTemporayMem", 0, 0, 0, OVT_MemListFree_TempObjects, 0, 0, 0, "Memory", "OpenVmTil" },
    { "freeCompilerTempMem", 0, 0, 0, OVT_MemListFree_CompilerTempObjects, 0, 0, 0, "Memory", "OpenVmTil" },
    { "freeLispTempMem", 0, 0, 0, OVT_MemListFree_LispTemp, 0, 0, 0, "Memory", "OpenVmTil" },
    { "freeSessionMem", 0, 0, 0, OVT_MemListFree_Session, 0, 0, 0, "Memory", "OpenVmTil" },
    { "freeAllTempMem", 0, 0, 0, OVT_FreeTempMem, 0, 0, 0, "Memory", "OpenVmTil" },

    { "_dup", "A.AA", 0, 0, CSL_Dup, CATEGORY_DUP | KEYWORD | CATEGORY_OP_STACK, T_ANY, 0, "Stack", "Root" },
    { "dup", "A.AA", 0, 0, CSL_Dup, IMMEDIATE | KEYWORD | CATEGORY_DUP | CATEGORY_OP_STACK, T_ANY, 0, "Stack", "Root" },
    { "ndup", 0, 0, 0, CSL_NDup, CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "drop", 0, 0, 0, CSL_Drop, IMMEDIATE | KEYWORD | CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "dropN", 0, 0, 0, CSL_DropN, IMMEDIATE | CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "_ndrop", 0, 0, 0, CSL_DropN, CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "pick", 0, 0, 0, CSL_Pick, IMMEDIATE | KEYWORD | CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "_swap", 0, 0, 0, CSL_Swap, 0, 0, 0, "Stack", "Root" },
    { "dsp", 0, 0, 0, CSL_Dsp, CATEGORY_OP_STACK, 0, 0, "Stack", "Root" },
    { "stackCheck", 0, 0, 0, DataStack_Check, 0, 0, 0, "Stack", "Root" },

    { "lisp", 0, 0, 0, ( block ) LO_Repl, 0, 0, 0, "List", "Root" },
    { "_(", 0, 0, 0, ( block ) LC_Read, IMMEDIATE | KEYWORD, 0, 0, "List", "Root" },
    { "eval", 0, 0, 0, ( block ) LC_Eval, IMMEDIATE | KEYWORD, 0, 0, "List", "Root" },
    { "printList", 0, 0, 0, ( block ) LC_PrintWithValue, 0, 0, 0, "List", "Root" },
    { "dupList", 0, 0, 0, ( block ) LC_DupList, 0, 0, 0, "List", "Root" },
    { "lcRestoreStack", 0, 0, 0, ( block ) LC_RestoreStack, 0, 0, 0, "List", "Root" },

    { "compileMode", 0, 0, 0, CSL_CompileMode, 0, 0, 0, "Interpreter", "Root" },
    { "finishDebugInfo", 0, 0, 0, CSL_FinishWordDebugInfo, 0, 0, 0, "Interpreter", "Root" },
    { "compileModeOn", 0, 0, 0, CSL_RightBracket, 0, 0, 0, "Interpreter", "Root" },
    { "asmModeOn", 0, 0, 0, CSL_AsmModeOn, 0, 0, 0, "Interpreter", "Root" },
    { "asmModeOff", 0, 0, 0, CSL_AsmModeOff, 0, 0, 0, "Interpreter", "Root" },
    { "compileModeOff", 0, 0, 0, CSL_LeftBracket, 0, 0, 0, "Interpreter", "Root" },
    { "//", 0, 0, 0, CSL_CommentToEndOfLine, IMMEDIATE | KEYWORD | COMMENT, 0, W_COMMENT, "Interpreter", "Root" },
    { "#!", 0, 0, 0, CSL_CommentToEndOfLine, IMMEDIATE | COMMENT, 0, W_COMMENT, "Interpreter", "Root" },
    { "*/", 0, 0, 0, CSL_NoOp, IMMEDIATE | COMMENT, 0, W_COMMENT, "Interpreter", "Root" },
    { "/*", 0, 0, 0, CSL_ParenthesisComment, IMMEDIATE | COMMENT, 0, W_COMMENT, "Interpreter", "Root" },
    { "eval", 0, 0, 0, CSL_Interpreter_EvalWord, 0, 0, 0, "Interpreter", "Root" },
    { "doWord", 0, 0, 0, CSL_DoWord, 0, 0, 0, "Interpreter", "Root" },
    { "tokenToWord", 0, 0, 0, CSL_TokenToWord, 0, 0, 0, "Interpreter", "Root" },
    { "interpretString", 0, 0, 0, CSL_InterpretString, 0, 0, 0, "Interpreter", "Root" },
    { "interpretNextToken", 0, 0, 0, CSL_InterpretNextToken, 0, 0, 0, "Interpreter", "Root" },
    { "interpreterRun", 0, 0, 0, CSL_InterpreterRun, 0, 0, 0, "Interpreter", "Root" },
    { "interpreterInit", 0, 0, 0, CSL_Interpreter_Init, 0, 0, 0, "Interpreter", "Root" },
    { "interpreterStop", 0, 0, 0, CSL_InterpreterStop, 0, 0, 0, "Interpreter", "Root" },
    { "interpreterIsDone", 0, 0, 0, CSL_Interpreter_IsDone, 0, 0, 0, "Interpreter", "Root" },
    { "interpreterDone", 0, 0, 0, CSL_Interpreter_Done, 0, 0, 0, "Interpreter", "Root" },
    { "interpret", 0, 0, 0, CSL_InterpreterRun, 0, 0, 0, "Interpreter", "Root" },
    { "interpretFile", 0, 0, 0, CSL_Interpret, 0, 0, 0, "Interpreter", "Root" },
    { "l:", 0, 0, 0, CSL_Interpret_ReadToList, 0, 0, 0, "Interpreter", "Root" },
    { "_lx_", 0, 0, 0, CSL_Interpret_List, 0, 0, 0, "Interpreter", "Root" },

    { "#", 0, 0, 0, CSL_PreProcessor, IMMEDIATE, 0, W_PREPROCESSOR, "Interpreter", "Root" },
    { "!", 0, 0, 0, CSL_CommentToEndOfLine, 0, 0, W_PREPROCESSOR, "PreProcessor", "Root" }, // in init.csl ; needed for script files starting with #! csl -s
    { "endif", 0, 0, 0, CSL_Endif_ConditionalInterpret, IMMEDIATE, 0, W_PREPROCESSOR, "PreProcessor", "Root" },
    { "else", 0, 0, 0, CSL_Else_ConditionalInterpret, IMMEDIATE, 0, W_PREPROCESSOR, "PreProcessor", "Root" },
    { "if", 0, 0, 0, CSL_If_ConditionalInterpret, IMMEDIATE, 0, W_PREPROCESSOR, "PreProcessor", "Root" },
    { "elif", 0, 0, 0, CSL_Elif_ConditionalInterpret, IMMEDIATE, 0, W_PREPROCESSOR, "PreProcessor", "Root" },
    { "define", 0, 0, 0, CSL_Define, IMMEDIATE, 0, W_PREPROCESSOR, "PreProcessor", "Root" },

    { "sm:", 0, 0, 0, CSL_StringMacro, 0, 0, 0, "Macro", "Root" },
    { "alias", 0, 0, 0, CSL_Alias, 0, 0, 0, "Macro", "Root" },
    { "tm:", 0, 0, 0, CSL_TextMacro, 0, 0, 0, "Macro", "Root" },

    { "name", 0, 0, 0, Word_Name, CATEGORY_OP_STACK, 0, 0, "Word", "Root" },
    { "wordNew", 0, 0, 0, CSL_Word_New, 0, 0, 0, "Word", "Root" },
    { "wNamespace", 0, 0, 0, Word_Namespace, CATEGORY_OP_STACK, 0, 0, "Word", "Root" },
    { "wordEval", 0, 0, 0, CSL_Word_Eval, 0, 0, 0, "Word", "Root" },
    { "wordRun", 0, 0, 0, CSL_Word_Run, 0, 0, 0, "Word", "Root" },
    { "run", 0, 0, 0, DataObject_Run, 0, 0, 0, "Word", "Root" },
    { "definition", 0, 0, 0, Word_Definition, CATEGORY_OP_STACK, 0, 0, "Word", "Root" },
    { "value", 0, 0, 0, Word_Value, CATEGORY_OP_STACK, 0, 0, "Word", "Root" },
    { "xt", 0, 0, 0, Word_Xt_LValue, CATEGORY_OP_STACK, 0, 0, "Word", "Root" },
    { "xt=", 0, 0, 0, Word_DefinitionEqual, 0, 0, 0, "Word", "Root" },
    { "wordFinish", 0, 0, 0, Word_Finish, 0, 0, 0, "Word", "Root" },
    { "wordAdd", 0, 0, 0, Word_Add, 0, 0, 0, "Word", "Root" },
    { "codeStart", 0, 0, 0, Word_CodeStart, 0, 0, 0, "Word", "Root" },
    { "codeSize", 0, 0, 0, Word_CodeSize, 0, 0, 0, "Word", "Root" },
    { "addrToWord", 0, 0, 0, AddressToWord, 0, 0, 0, "Word", "Root" },
    { "purgeWordName", 0, 0, 0, CSL_Namespaces_PurgeWordExactName, 0, 0, 0, "Word", "Root" },
    { "purgeWordIfContainsName", 0, 0, 0, CSL_Namespaces_PurgeWordIfContainsName, 0, 0, 0, "Word", "Root" },
    { "wordNsListPrint", 0, 0, 0, CSL_Namespace_PrintWordList, 0, 0, 0, "Word", "Root" },

    // Dynamic Object - DObject
    { "dobject", 0, 0, 0, CSL_SetPropertiesAsDObject, 0, 0, 0, "DObject", "Root" },
    { "clone", 0, 0, 0, CSL_DObject_Clone, 0, 0, 0, "DObject", "Root" },
    { "new", 0, 0, 0, CSL_DObject_New, 0, 0, 0, "DObject", "Root" },

    // this section can be implemented by lower level calls - internally
    { "word", 0, 0, 0, CSL_Word, 0, 0, 0, "Reserved", "Compiler" },
    { ":", 0, 0, 0, CSL_Colon, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" },
    { "semi", 0, 0, 0, CSL_SemiColon, KEYWORD, 0, 0, "Reserved", "Compiler" },
    { ";", 0, 0, 0, CSL_SemiColon, IMMEDIATE | SYNTACTIC | KEYWORD, 0, 0, "Reserved", "Compiler" },
    { "}", 0, 0, 0, ( block ) CSL_EndBlock, IMMEDIATE | BLOCK_DELIMITER | KEYWORD, 0, 0, "Reserved", "Compiler" }, // moved to init.csl and renamed below
    { "{", 0, 0, 0, ( block ) CSL_BeginBlock, IMMEDIATE | BLOCK_DELIMITER | KEYWORD, 0, 0, "Reserved", "Compiler" }, // moved to init.csl and renamed below
    { "end", 0, 0, 0, CSL_EndBlock, IMMEDIATE | BLOCK_DELIMITER | KEYWORD, 0, 0, "Reserved", "Compiler" },
    { "immediate", 0, 0, 0, CSL_Immediate, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" },
    //{ "stackVariable", 0, 0, 0, CSL_StackVariable, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" },
    { "syntactic", 0, 0, 0, CSL_Syntactic, IMMEDIATE | KEYWORD, 0, 0, "Reserved", "Compiler" },

    { "dlsym:", 0, 0, 0, CSL_Dlsym, 0, 0, 0, "Reserved", "Compiler" },
    { "keyword", 0, 0, 0, CSL_Keyword, IMMEDIATE, 0, 0, "Reserved", "Compiler" },
    { "swap", 0, 0, 0, CSL_Swap, IMMEDIATE, 0, 0, "Reserved", "Compiler" },
    { "|}", 0, 0, 0, _CSL_RightBracket, IMMEDIATE, 0, 0, "Reserved", "Compiler" },
    { "{|", 0, 0, 0, CSL_LeftBracket, IMMEDIATE, 0, 0, "Reserved", "Compiler" },

    { "c_syntaxOn", 0, 0, 0, CSL_C_Syntax_On, IMMEDIATE, 0, 0, "Compiler", "Root" }, // put this here so Compiler will be in Root namespace and Compiler will close to the top
    { "c_syntaxOff", 0, 0, 0, CSL_C_Syntax_Off, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "postfixOn", 0, 0, 0, CSL_PostfixModeOn, IMMEDIATE | KEYWORD, 0, 0, "Compiler", "Root" },
    { "goto", 0, 0, 0, CSL_Goto, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "continue", 0, 0, 0, CSL_Continue, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "return", 0, 0, 0, CSL_Return, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "break", 0, 0, 0, CSL_Break, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "noop", 0, 0, 0, CSL_NoOp, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "macro", 0, 0, 0, CSL_Word, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "_variable", 0, 0, 0, CSL_Variable, 0, 0, 0, "Compiler", "Root" },
    { "variable", 0, 0, 0, CSL_Variable, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "_constant", 0, 0, 0, CSL_Constant, 0, 0, 0, "Compiler", "Root" },
    { "constant", 0, 0, 0, CSL_Constant, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "literal", 0, 0, 0, CSL_Literal, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "_literal", 0, 0, 0, CSL_Literal, 0, 0, 0, "Compiler", "Root" },
    { "_end", 0, 0, 0, CSL_EndBlock, BLOCK_DELIMITER, 0, 0, "Compiler", "Root" },
    { "begin", 0, 0, 0, ( block ) CSL_BeginBlock, BLOCK_DELIMITER, 0, 0, "Compiler", "Root" },
    { "Here", "V.I", 0, 0, CSL_Here, CATEGORY_OP_STACK, T_INT, 0, "Compiler", "Root" }, //anything that pushes it result onto the stack should be CATEGORY_OP !?
    { "code", 0, 0, 0, CSL_Code, 0, 0, 0, "Compiler", "Root" },
    { "_immediate", 0, 0, 0, CSL_Immediate, 0, 0, 0, "Compiler", "Root" },
    { "?immediate", 0, 0, 0, CSL_IsImmediate, INFIXABLE, 0, 0, "Compiler", "Root" },
    { "inline", 0, 0, 0, CSL_Inline, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "typeSignature", "S", 0, 0, CSL_Set_TypeSignature, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "_prefix", 0, 0, 0, CSL_Prefix, 0, 0, 0, "Compiler", "Root" },
    { "prefix", 0, 0, 0, CSL_Prefix, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "nprefix", 0, 0, 0, CSL_NPrefix, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "infixOn", 0, 0, 0, CSL_InfixModeOn, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "infixOff", 0, 0, 0, CSL_InfixModeOff, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "prefixOn", 0, 0, 0, CSL_PrefixModeOn, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "prefixOff", 0, 0, 0, CSL_PrefixModeOff, IMMEDIATE, 0, 0, "Compiler", "Root" },
    { "debugWord", 0, 0, 0, CSL_DebugWord, 0, 0, 0, "Compiler", "Root" },
    { "@", 0, 0, MOV, CSL_Peek, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_LOAD | CATEGORY_OP_1_ARG, 0, 0, "Compiler", "Root" }, // fetch
    { "load", 0, 0, MOV, CSL_Peek, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_LOAD | CATEGORY_OP_1_ARG, 0, 0, "Compiler", "Root" },
    { "peek", 0, 0, MOV, CSL_Peek, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_LOAD | CATEGORY_OP_1_ARG, 0, 0, "Compiler", "Root" },
    { "get", 0, 0, MOV, CSL_Peek, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_LOAD | CATEGORY_OP_1_ARG, 0, 0, "Compiler", "Root" },
    { "@=", 0, 0, 0, CSL_AtEqual, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_ORDERED | CATEGORY_OP_1_ARG, 0, 0, "Compiler", "Root" },
    { "!", 0, 0, MOV, CSL_Store, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_STORE, 0, 0, "Compiler", "Root" },
    { "=", "XA.V", 0, MOV, CSL_Poke, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_EQUAL | INFIXABLE | KEYWORD, 0, 0, "Compiler", "Root" },
    { "poke", "XA.V", 0, MOV, CSL_Poke, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_EQUAL, 0, 0, "Compiler", "Root" },
    { "set", "XA.V", 0, MOV, CSL_Poke, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_EQUAL, 0, 0, "Compiler", "Root" },
    { "store", "AX.V", 0, MOV, CSL_Store, IMMEDIATE | CATEGORY_OP | CATEGORY_OP_STORE, 0, 0, "Compiler", "Root" },
    { "quote", 0, 0, 0, CSL_SingleQuote, KEYWORD, 0, 0, "Compiler", "Root" },
    { "_tick", 0, 0, 0, CSL_SingleQuote, KEYWORD, 0, 0, "Compiler", "Root" },
    { "token", 0, 0, 0, CSL_Token, 0, 0, 0, "Compiler", "Root" },
    { "tokenQID", 0, 0, 0, CSL_TokenQID, 0, 0, 0, "Compiler", "Root" },
    { "ftoken", 0, 0, 0, CSL_FilenameToken, 0, 0, 0, "Compiler", "Root" },
    { "getStringToEndOfLine", 0, 0, 0, String_GetStringToEndOfLine, 0, 0, 0, "Compiler", "Root" },
    { "sourceCodeInit", 0, 0, 0, CSL_SourceCode_Init, 0, 0, 0, "Compiler", "Root" },
    { "sourceCodeOn", 0, 0, 0, CSL_Lexer_SourceCodeOn, 0, 0, 0, "Compiler", "Root" },
    //{ ")", 0, 0, 0, CSL_NoOp, IMMEDIATE | KEYWORD, NO_OP_WORD|RIGHT_PAREN, 0, "Compiler", "Root" },
    { ")", 0, 0, 0, CSL_C_Comma, IMMEDIATE | KEYWORD | RIGHT_PAREN, 0, 0, "Compiler", "Root" },

    { "compileByte", 0, 0, 0, Compile_Int8, 0, 0, 0, "Compiling", "Compiler" },
    { "compileInt16", 0, 0, 0, Compile_Int16, 0, 0, 0, "Compiling", "Compiler" },
    { "compileInt32", 0, 0, 0, Compile_Int32, 0, 0, 0, "Compiling", "Compiler" },
    { "compileInt64", 0, 0, 0, CompileInt64, 0, 0, 0, "Compiling", "Compiler" },
    { "_compileCall", 0, 0, 0, CompileCall, 0, 0, 0, "Compiling", "Compiler" },
    { "_compileWord", 0, 0, 0, CompileACSLWord, 0, 0, 0, "Compiling", "Compiler" },
    //{ "_compileThisWord", 0, 0, 0, Word_Compile_CurrentRunningWord, 0, 0, 0, "Compiling", "Compiler" },
    //{ "compileThisWord", 0, 0, 0, Word_Compile_CurrentRunningWord, IMMEDIATE, 0, 0, "Compiling", "Compiler" },
    { "peekReg", 0, 0, 0, CSL_PeekReg, 0, 0, 0, "Compiling", "Compiler" },
    { "pokeRegWithValue", 0, 0, 0, CSL_PokeRegWithValue, 0, 0, 0, "Compiling", "Compiler" },
    { "pokeRegAtAddress", 0, 0, 0, CSL_PokeRegAtAddress, 0, 0, 0, "Compiling", "Compiler" },

    { 0 }
} ;



